service: adamdawkins

image: adamdawkins

servers:
  app:
    - 159.65.87.47
  web:
    - 159.65.87.47

<%# proxy: %>
<%#   ssl: true %>
<%#   host: myapp.example.com %>

registry:
  username: local
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - "app_storage:/app/storage"

builder:
    arch: amd64

