service: adamdawkins_com
image: circusfrog/adamdawkinscom
servers:
  - 159.65.87.47
registry:
  username: circusfrog
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY
